-- Migración: grupos de invitación para chats

create table if not exists public.chat_invite_groups (
  id bigint generated by default as identity primary key,
  inviter_id bigint not null references public.usuarios(id) on delete cascade,
  title text,
  created_at timestamptz default now()
);

create index if not exists idx_chat_invite_groups_inviter on public.chat_invite_groups(inviter_id);
