-- Migración: invitaciones a chats

create table if not exists public.chat_invitations (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.chat_invite_groups(id) on delete cascade,
  invitee_id bigint not null references public.usuarios(id) on delete cascade,
  status text default 'pending', -- pending|accepted|rejected
  responded_at timestamptz
);

create index if not exists idx_chat_invitations_group on public.chat_invitations(group_id);
create index if not exists idx_chat_invitations_invitee on public.chat_invitations(invitee_id);
