-- Migración: participantes de chat

create table if not exists public.chat_participants (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats(id) on delete cascade,
  user_id bigint not null references public.usuarios(id) on delete cascade,
  joined_at timestamptz default now(),
  unique (chat_id, user_id)
);

create index if not exists idx_chat_participants_chat on public.chat_participants(chat_id);
create index if not exists idx_chat_participants_user on public.chat_participants(user_id);
