-- Migración: crear tabla de chats

create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  title text,
  owner_id bigint not null references public.usuarios(id) on delete cascade,
  is_group boolean default true,
  created_at timestamptz default now()
);

create index if not exists idx_chats_owner on public.chats(owner_id);
