-- Migración: mensajes dentro de chats

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats(id) on delete cascade,
  sender_id bigint not null references public.usuarios(id) on delete cascade,
  content text not null,
  created_at timestamptz default now()
);

create index if not exists idx_chat_messages_chat on public.chat_messages(chat_id);
create index if not exists idx_chat_messages_sender on public.chat_messages(sender_id);
