-- Migración: crear tabla messages para chat entre usuarios

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id bigint not null references public.usuarios(id) on delete cascade,
  receiver_id bigint not null references public.usuarios(id) on delete cascade,
  content text not null,
  "read" boolean default false,
  created_at timestamptz default now()
);

create index if not exists idx_messages_receiver on public.messages(receiver_id);
create index if not exists idx_messages_sender on public.messages(sender_id);
